-- MySQL Script generated by MySQL Workbench
-- Mon Mar 21 14:31:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `restaurante` ;

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante` DEFAULT CHARACTER SET utf8 ;
USE `restaurante` ;

-- -----------------------------------------------------
-- Table `restaurante`.`Plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Plato` (
  `idPlato` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `cantidad_plato` INT(100) NOT NULL,
  `precio` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idPlato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Bebidas` (
  `idBebidas` INT NOT NULL AUTO_INCREMENT,
  `nombre_bebida` VARCHAR(45) NOT NULL,
  `tipo_botella` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `tamano` VARCHAR(20) NOT NULL,
  `precio_unidad` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idBebidas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATE NOT NULL,
  `precio_total` INT NOT NULL,
  `Plato_idPlato` INT NOT NULL,
  `Bebidas_idBebidas` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Plato1_idx` (`Plato_idPlato` ASC) ,
  INDEX `fk_Pedido_Bebidas1_idx` (`Bebidas_idBebidas` ASC) ,
  CONSTRAINT `fk_Pedido_Plato1`
    FOREIGN KEY (`Plato_idPlato`)
    REFERENCES `restaurante`.`Plato` (`idPlato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Bebidas1`
    FOREIGN KEY (`Bebidas_idBebidas`)
    REFERENCES `restaurante`.`Bebidas` (`idBebidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `nombre_usuario` VARCHAR(100) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

